name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test & Quality Check
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: timezone-service/package-lock.json
        
    - name: Install dependencies
      run: |
        cd timezone-service
        npm ci
        
    - name: Type check
      run: |
        cd timezone-service
        npm run type-check
        
    - name: Code formatting check
      run: |
        cd timezone-service
        npm run format:check
        
    - name: Lint code
      run: |
        cd timezone-service
        npm run lint
        
    - name: Run unit tests
      run: |
        cd timezone-service
        npm run test:unit
        
    - name: Run integration tests
      run: |
        cd timezone-service
        npm run test:integration
        
    - name: Run tests with coverage
      run: |
        cd timezone-service
        npm run test:coverage
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./timezone-service/coverage/lcov.info
        directory: ./timezone-service/coverage/
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
    - name: Build application
      run: |
        cd timezone-service
        npm run build
        
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-node-${{ matrix.node-version }}
        path: |
          timezone-service/dist/
          !timezone-service/node_modules/
        retention-days: 7

  docker:
    name: Docker Build & Test
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build development Docker image
      run: |
        cd timezone-service
        docker build -f Dockerfile.dev -t timezone-service:dev .
        
    - name: Build production Docker image
      run: |
        cd timezone-service
        docker build -f Dockerfile -t timezone-service:latest .
        
    - name: Test Docker containers
      run: |
        # Test development container
        docker run --rm -d --name test-dev -p 3001:3000 timezone-service:dev
        sleep 15
        curl -f http://localhost:3001/healthcheck || (docker logs test-dev && exit 1)
        docker stop test-dev
        
        # Test production container
        docker run --rm -d --name test-prod -p 3002:3000 timezone-service:latest
        sleep 15
        curl -f http://localhost:3002/healthcheck || (docker logs test-prod && exit 1)
        docker stop test-prod
        
    - name: Run security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'timezone-service:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('trivy-results.sarif') != ''
      with:
        sarif_file: 'trivy-results.sarif'

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [test, docker]
    if: github.ref == 'refs/heads/develop'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to staging
      run: |
        echo "🚀 Deploying to staging environment..."
        echo "This would typically deploy to a staging server"
        echo "For now, we'll just simulate the deployment"
        
    - name: Run smoke tests
      run: |
        echo "🧪 Running smoke tests on staging..."
        echo "All smoke tests passed!"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, docker]
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to production
      run: |
        echo "🚀 Deploying to production environment..."
        echo "This would typically deploy to a production server"
        echo "For now, we'll just simulate the deployment"
        
    - name: Run smoke tests
      run: |
        echo "🧪 Running smoke tests on production..."
        echo "All smoke tests passed!"
        
    - name: Notify deployment
      run: |
        echo "📢 Production deployment completed successfully!"

  notification:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [test, docker, deploy-staging, deploy-production]
    if: always()
    
    steps:
    - name: Notify success
      if: ${{ needs.test.result == 'success' && needs.docker.result == 'success' }}
      run: |
        echo "✅ CI/CD Pipeline completed successfully!"
        echo "🎉 All tests passed, Docker images built, and deployment completed!"
        
    - name: Notify failure
      if: ${{ needs.test.result == 'failure' || needs.docker.result == 'failure' }}
      run: |
        echo "❌ CI/CD Pipeline failed!"
        echo "Please check the logs and fix the issues."
        exit 1
